[package]
name = "myonsandbox"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
myoncore.workspace = true
tracing.workspace = true
winit.workspace = true
